/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GCMS.Gradle.IgorCabral;

public class Library {
    public boolean someLibraryMethod() {
        return false;  /*devia dar erro ao subir */
      
    }
}
